services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TZ=${TZ}
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
