services:
  stocks:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocks
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
    volumes:
      - /srv/docker/stocks/data:/data
    networks:
      - edge

networks:
  edge:
    name: edge
    external: true
