services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - edge
    environment:
      - TZ=${TZ}
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - edge
    ports:
      - "25565:25565"
      - "34197:34197/udp"
      - "80:80"
      - "443:443"
    volumes:
      - /srv/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/docker/nginx/streams.d:/etc/nginx/streams.d:ro
      - /srv/docker/nginx/certs:/etc/nginx/certs:ro

  acme:
    image: neilpang/acme.sh:latest
    container_name: acme
    restart: unless-stopped
    environment:
      - CF_Token=${CF_TOKEN}
      - ACME_DOMAIN=${ACME_DOMAIN}
    volumes:
      - acme_data:/acme.sh
      - /srv/docker/nginx/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint:
      - sh
      - -c
      - |
        set -e
        apk add --no-cache docker-cli
        acme.sh --set-default-ca --server letsencrypt
        if [ ! -f "/acme.sh/${ACME_DOMAIN}_ecc/${ACME_DOMAIN}.cer" ]; then
          acme.sh --issue --server letsencrypt --dns dns_cf -d "$ACME_DOMAIN" -d "*.$ACME_DOMAIN" --keylength ec-256
        fi
        acme.sh --install-cert -d "$ACME_DOMAIN" --ecc \
          --key-file "/certs/$ACME_DOMAIN/privkey.pem" \
          --fullchain-file "/certs/$ACME_DOMAIN/fullchain.pem" \
          --reloadcmd "docker exec nginx-proxy nginx -s reload"
        exec acme.sh --daemon


networks:
  edge:
    name: edge
    driver: bridge

volumes:
  acme_data:
