services:
  router:
    image: itzg/mc-router
    restart: unless-stopped
    cpuset: "0-1"
    environment:
      IN_DOCKER: true
      AUTO_SCALE_DOWN: true
      AUTO_SCALE_UP: true
      AUTO_SCALE_DOWN_AFTER: 2h
      AUTO_SCALE_ASLEEP_MOTD: "Server is asleep. Join again to wake it up!"
      API_BINDING: ":8080"
      METRICS_BACKEND: prometheus
      RECORD_LOGINS: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge
  zinnberlycraft:
    image: itzg/minecraft-server:latest
    cpuset: "0-1"
    environment:
      EULA: "TRUE"
      VERSION: "26.2"
      VIEW_DISTANCE: "12"
      MOTD: "§l§cWelcome§r to our §aAwesome§r Server"
    volumes:
      - /srv/docker/game-servers/minecraft/zinnberlycraft/data:/data
    restart: unless-stopped
    labels:
      mc-router.host: "${ZINNBERLYCRAFT_HOST}"
    networks:
      - edge
  foreverworld:
    image: itzg/minecraft-server
    cpuset: "0-1"
    environment:
      EULA: "TRUE"
      MOTD: "${FOREVERWORLD_MOTD}"
      SIMULATION_DISTANCE: "12"
      VIEW_DISTANCE: "12"
      VERSION: "26.2"
      difficulty: "normal"
    labels:
      mc-router.host: "${FOREVERWORLD_HOST}"
    volumes:
      - /srv/docker/game-servers/minecraft/forever/data:/data
    networks:
      - edge
  # atm11:
  #   image: itzg/minecraft-server:java25
  #   environment:
  #     EULA: "TRUE"
  #     MOTD: "${ATM11_MOTD}"
  #     VIEW_DISTANCE: "10"
  #     VERSION: "26.1.2"
  #     difficulty: "normal"
  #     CF_API_KEY_FILE: /run/secrets/cf_api_key
  #     MODPACK_PLATFORM: AUTO_CURSEFORGE
  #     CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-11/files/8431787
  #     ALLOW_FLIGHT: "TRUE"
  #     MEMORY: "8G"
  #     USE_AIKAR_FLAGS: "TRUE"
  #     MAX_TICK_TIME: "-1"
  #   labels:
  #     mc-router.host: "${ATM11_HOST}"
  #   volumes:
  #     - /srv/docker/game-servers/minecraft/atm11/data:/data
  #   networks:
  #     - edge
  #   secrets:
  #     - cf_api_key
  gtnh:
    # java25 is recommended for GTNH 2.8.0+
    image: itzg/minecraft-server:java25
    environment:
      EULA: "TRUE"
      TYPE: GTNH
      GTNH_PACK_VERSION: "2.8.4"
      # set to "true" after the first successful start to skip the install/update check
      SKIP_GTNH_UPDATE_CHECK: "true"
      MOTD: "GT: New Horizons 2.8.4"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "TRUE"
      # GTNH server defaults
      DIFFICULTY: "hard"
      LEVEL_TYPE: "rwg"
      VIEW_DISTANCE: "8"
      SPAWN_PROTECTION: "1"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_FLIGHT: "TRUE"
      ENABLE_WHITELIST: "TRUE"
      WHITELIST: "colepez"
      EXISTING_WHITELIST_FILE: MERGE
    mem_limit: 10g
    labels:
      mc-router.host: "${GTNH_HOST}"
    volumes:
      - /srv/docker/game-servers/minecraft/gtnh/data:/data
    restart: unless-stopped
    networks:
      - edge

networks:
  edge:
    name: edge
    external: true

secrets:
  cf_api_key:
    file: /srv/docker/game-servers/minecraft/curseforgeapi/api.env
